# Select

1. Создать подключения к базе данных с помощью библиотеки sqlite3.

In [25]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('../data/checking-logs.sqlite')

2. Получить схему таблицы pageviews.

In [26]:
pageviews_schema = pd.read_sql('PRAGMA table_info(pageviews)', conn)

pageviews_schema

   cid      name       type  notnull dflt_value  pk
0    0     index    INTEGER        0       None   0
1    1       uid       TEXT        0       None   0
2    2  datetime  TIMESTAMP        0       None   0

3. Получить первые 10 строк таблицы pageviews.

In [27]:
pageviews = pd.read_sql('SELECT * FROM pageviews', conn)

pageviews.head(10)

   index      uid                    datetime
0      0  admin_1  2020-04-17 12:01:08.463179
1      1  admin_1  2020-04-17 12:01:23.743946
2      2  admin_3  2020-04-17 12:17:39.287778
3      3  admin_3  2020-04-17 12:17:40.001768
4      4  admin_1  2020-04-17 12:27:30.646665
5      5  admin_1  2020-04-17 12:35:44.884757
6      6  admin_1  2020-04-17 12:35:52.735016
7      7  admin_3  2020-04-17 12:36:21.401412
8      8  admin_3  2020-04-17 12:36:22.023355
9      9  admin_1  2020-04-17 13:55:19.129243

4. Получить подтаблицу с помощью одного запроса.

In [28]:
query = """
SELECT uid, datetime
FROM pageviews
WHERE uid > "user_"
ORDER BY 1
"""

pageviews = pd.read_sql(query, conn)

pageviews.set_index("datetime", inplace=True)
pageviews.rename_axis(index={'datetime': 'DatetimeIndex'}, inplace=True)

pageviews.head(10)

                               uid
DatetimeIndex
2020-04-26 21:53:59.624136  user_1
2020-04-26 22:06:19.478143  user_1
2020-04-26 22:12:09.614497  user_1
2020-04-30 19:29:01.831635  user_1
2020-05-05 20:26:32.894852  user_1
2020-05-07 18:51:12.029577  user_1
2020-05-11 21:56:54.292312  user_1
2020-05-14 22:56:14.464582  user_1
2020-05-14 23:59:38.758438  user_1
2020-05-15 00:05:27.798227  user_1

5. Закрыть соединение с базой данных.

In [29]:
conn.close()